### ISSUE TITLE
Compatibility with jinja?

### ISSUE THREAD

**Issue by wavefrontshaping** [papis/papis-rofi#1]
Hi,

I use jinja in my config file, and when I try to use `papis rofi`, I do not see the actual information about the paper in the list but the jinja code without the outer brakets, like `{doc["title"]}` instead of the actual title.

Can it be compatible with jinja templating?

Thanks!

Sebastien

**Comment by alejandrogallo** [comment]
Since we deprecated jinja from papis for the moment until we get a more modular templating
engine, this issue is not anymore at hand..

Thank you very much Sebastien for your interest!
